/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List all detected threats
 */
export const ListThreatsQueryParams = zod.object({
  "severity": zod.enum(['critical', 'high', 'medium', 'low']).optional(),
  "status": zod.enum(['active', 'blocked', 'investigating', 'resolved']).optional(),
  "limit": zod.coerce.number().optional()
})

export const ListThreatsResponseItem = zod.object({
  "id": zod.number(),
  "type": zod.string(),
  "severity": zod.enum(['critical', 'high', 'medium', 'low']),
  "status": zod.enum(['active', 'blocked', 'investigating', 'resolved']),
  "sourceIp": zod.string(),
  "targetSystem": zod.string(),
  "description": zod.string(),
  "aiExplanation": zod.string().nullish(),
  "aiConfidence": zod.number().nullish(),
  "mitigationSteps": zod.string().nullish(),
  "country": zod.string().nullish(),
  "attackVector": zod.string().nullish(),
  "affectedUsers": zod.number().nullish(),
  "detectedAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})
export const ListThreatsResponse = zod.array(ListThreatsResponseItem)


/**
 * @summary Create a new threat record
 */
export const CreateThreatBody = zod.object({
  "type": zod.string(),
  "severity": zod.enum(['critical', 'high', 'medium', 'low']),
  "sourceIp": zod.string(),
  "targetSystem": zod.string(),
  "description": zod.string(),
  "country": zod.string().optional(),
  "attackVector": zod.string().optional(),
  "affectedUsers": zod.number().optional()
})


/**
 * @summary Get a specific threat
 */
export const GetThreatParams = zod.object({
  "id": zod.coerce.number()
})

export const GetThreatResponse = zod.object({
  "id": zod.number(),
  "type": zod.string(),
  "severity": zod.enum(['critical', 'high', 'medium', 'low']),
  "status": zod.enum(['active', 'blocked', 'investigating', 'resolved']),
  "sourceIp": zod.string(),
  "targetSystem": zod.string(),
  "description": zod.string(),
  "aiExplanation": zod.string().nullish(),
  "aiConfidence": zod.number().nullish(),
  "mitigationSteps": zod.string().nullish(),
  "country": zod.string().nullish(),
  "attackVector": zod.string().nullish(),
  "affectedUsers": zod.number().nullish(),
  "detectedAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary Update threat status
 */
export const UpdateThreatStatusParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateThreatStatusBody = zod.object({
  "status": zod.enum(['active', 'blocked', 'investigating', 'resolved'])
})

export const UpdateThreatStatusResponse = zod.object({
  "id": zod.number(),
  "type": zod.string(),
  "severity": zod.enum(['critical', 'high', 'medium', 'low']),
  "status": zod.enum(['active', 'blocked', 'investigating', 'resolved']),
  "sourceIp": zod.string(),
  "targetSystem": zod.string(),
  "description": zod.string(),
  "aiExplanation": zod.string().nullish(),
  "aiConfidence": zod.number().nullish(),
  "mitigationSteps": zod.string().nullish(),
  "country": zod.string().nullish(),
  "attackVector": zod.string().nullish(),
  "affectedUsers": zod.number().nullish(),
  "detectedAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary Simulate a new cyber attack event
 */
export const SimulateThreatBody = zod.object({
  "attackType": zod.string().nullish()
})


/**
 * @summary List security events
 */
export const ListEventsQueryParams = zod.object({
  "limit": zod.coerce.number().optional(),
  "threatId": zod.coerce.number().optional()
})

export const ListEventsResponseItem = zod.object({
  "id": zod.number(),
  "threatId": zod.number().nullish(),
  "eventType": zod.string(),
  "sourceIp": zod.string(),
  "targetSystem": zod.string(),
  "severity": zod.string(),
  "details": zod.string(),
  "timestamp": zod.coerce.date()
})
export const ListEventsResponse = zod.array(ListEventsResponseItem)


/**
 * @summary Upload CSV log file for analysis
 */
export const UploadEventsCsvBody = zod.object({
  "csvContent": zod.string(),
  "filename": zod.string().optional()
})

export const UploadEventsCsvResponse = zod.object({
  "totalRows": zod.number(),
  "threatsDetected": zod.number(),
  "criticalCount": zod.number(),
  "highCount": zod.number(),
  "mediumCount": zod.number(),
  "lowCount": zod.number(),
  "summary": zod.string(),
  "threats": zod.array(zod.object({
  "id": zod.number(),
  "type": zod.string(),
  "severity": zod.enum(['critical', 'high', 'medium', 'low']),
  "status": zod.enum(['active', 'blocked', 'investigating', 'resolved']),
  "sourceIp": zod.string(),
  "targetSystem": zod.string(),
  "description": zod.string(),
  "aiExplanation": zod.string().nullish(),
  "aiConfidence": zod.number().nullish(),
  "mitigationSteps": zod.string().nullish(),
  "country": zod.string().nullish(),
  "attackVector": zod.string().nullish(),
  "affectedUsers": zod.number().nullish(),
  "detectedAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
}))
})


/**
 * @summary Get dashboard summary statistics
 */
export const GetDashboardSummaryResponse = zod.object({
  "activeThreats": zod.number(),
  "blockedThreats": zod.number(),
  "criticalAlerts": zod.number(),
  "totalEvents": zod.number(),
  "threatScore": zod.number(),
  "aiConfidenceAvg": zod.number(),
  "suspiciousDevices": zod.number(),
  "monitoringStatus": zod.string(),
  "threatsLast24h": zod.number(),
  "resolvedToday": zod.number()
})


/**
 * @summary Get threat activity timeline for the last 24 hours
 */
export const GetThreatTimelineResponseItem = zod.object({
  "hour": zod.string(),
  "critical": zod.number(),
  "high": zod.number(),
  "medium": zod.number(),
  "low": zod.number(),
  "total": zod.number()
})
export const GetThreatTimelineResponse = zod.array(GetThreatTimelineResponseItem)


/**
 * @summary Get threat count by severity
 */
export const GetSeverityBreakdownResponseItem = zod.object({
  "severity": zod.string(),
  "count": zod.number(),
  "percentage": zod.number()
})
export const GetSeverityBreakdownResponse = zod.array(GetSeverityBreakdownResponseItem)


/**
 * @summary Get threat count by attack type
 */
export const GetAttackTypeBreakdownResponseItem = zod.object({
  "type": zod.string(),
  "count": zod.number()
})
export const GetAttackTypeBreakdownResponse = zod.array(GetAttackTypeBreakdownResponseItem)


/**
 * @summary List AI-generated security recommendations
 */
export const ListRecommendationsResponseItem = zod.object({
  "id": zod.number(),
  "threatId": zod.number().nullish(),
  "title": zod.string(),
  "description": zod.string(),
  "priority": zod.enum(['immediate', 'high', 'medium', 'low']),
  "actionType": zod.string(),
  "isApplied": zod.boolean(),
  "createdAt": zod.coerce.date()
})
export const ListRecommendationsResponse = zod.array(ListRecommendationsResponseItem)


/**
 * @summary Trigger AI recommendation generation for current threats
 */
export const GenerateRecommendationsBody = zod.object({
  "threatIds": zod.array(zod.number()).optional()
})

export const GenerateRecommendationsResponseItem = zod.object({
  "id": zod.number(),
  "threatId": zod.number().nullish(),
  "title": zod.string(),
  "description": zod.string(),
  "priority": zod.enum(['immediate', 'high', 'medium', 'low']),
  "actionType": zod.string(),
  "isApplied": zod.boolean(),
  "createdAt": zod.coerce.date()
})
export const GenerateRecommendationsResponse = zod.array(GenerateRecommendationsResponseItem)


/**
 * @summary Mark a recommendation as applied
 */
export const ApplyRecommendationParams = zod.object({
  "id": zod.coerce.number()
})

export const ApplyRecommendationResponse = zod.object({
  "id": zod.number(),
  "threatId": zod.number().nullish(),
  "title": zod.string(),
  "description": zod.string(),
  "priority": zod.enum(['immediate', 'high', 'medium', 'low']),
  "actionType": zod.string(),
  "isApplied": zod.boolean(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary List all conversations
 */
export const ListOpenaiConversationsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "createdAt": zod.coerce.date()
})
export const ListOpenaiConversationsResponse = zod.array(ListOpenaiConversationsResponseItem)


/**
 * @summary Create a new conversation
 */
export const CreateOpenaiConversationBody = zod.object({
  "title": zod.string()
})


/**
 * @summary Get conversation with messages
 */
export const GetOpenaiConversationParams = zod.object({
  "id": zod.coerce.number()
})

export const GetOpenaiConversationResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "createdAt": zod.coerce.date(),
  "messages": zod.array(zod.object({
  "id": zod.number(),
  "conversationId": zod.number(),
  "role": zod.string(),
  "content": zod.string(),
  "createdAt": zod.coerce.date()
}))
})


/**
 * @summary Delete a conversation
 */
export const DeleteOpenaiConversationParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary List messages in a conversation
 */
export const ListOpenaiMessagesParams = zod.object({
  "id": zod.coerce.number()
})

export const ListOpenaiMessagesResponseItem = zod.object({
  "id": zod.number(),
  "conversationId": zod.number(),
  "role": zod.string(),
  "content": zod.string(),
  "createdAt": zod.coerce.date()
})
export const ListOpenaiMessagesResponse = zod.array(ListOpenaiMessagesResponseItem)


/**
 * @summary Send a message to the AI security copilot
 */
export const SendOpenaiMessageParams = zod.object({
  "id": zod.coerce.number()
})

export const SendOpenaiMessageBody = zod.object({
  "content": zod.string()
})


