/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { Threat } from './threat';
export interface CsvAnalysisResult {
    totalRows: number;
    threatsDetected: number;
    criticalCount: number;
    highCount: number;
    mediumCount: number;
    lowCount: number;
    summary: string;
    threats: Threat[];
}
//# sourceMappingURL=csvAnalysisResult.d.ts.map