/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface DashboardSummary {
    activeThreats: number;
    blockedThreats: number;
    criticalAlerts: number;
    totalEvents: number;
    threatScore: number;
    aiConfidenceAvg: number;
    suspiciousDevices: number;
    monitoringStatus: string;
    threatsLast24h: number;
    resolvedToday: number;
}
//# sourceMappingURL=dashboardSummary.d.ts.map