/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
export type ListThreatsStatus = typeof ListThreatsStatus[keyof typeof ListThreatsStatus];
export declare const ListThreatsStatus: {
    readonly active: "active";
    readonly blocked: "blocked";
    readonly investigating: "investigating";
    readonly resolved: "resolved";
};
//# sourceMappingURL=listThreatsStatus.d.ts.map