/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
export type ListThreatsSeverity = typeof ListThreatsSeverity[keyof typeof ListThreatsSeverity];
export declare const ListThreatsSeverity: {
    readonly critical: "critical";
    readonly high: "high";
    readonly medium: "medium";
    readonly low: "low";
};
//# sourceMappingURL=listThreatsSeverity.d.ts.map