/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { ListThreatsSeverity } from './listThreatsSeverity';
import type { ListThreatsStatus } from './listThreatsStatus';
export type ListThreatsParams = {
    severity?: ListThreatsSeverity;
    status?: ListThreatsStatus;
    limit?: number;
};
//# sourceMappingURL=listThreatsParams.d.ts.map