/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { OpenaiMessage } from './openaiMessage';
export interface OpenaiConversationWithMessages {
    id: number;
    title: string;
    createdAt: Date;
    messages: OpenaiMessage[];
}
//# sourceMappingURL=openaiConversationWithMessages.d.ts.map