/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface OpenaiError {
    error: string;
}
//# sourceMappingURL=openaiError.d.ts.map