/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface OpenaiMessage {
    id: number;
    conversationId: number;
    role: string;
    content: string;
    createdAt: Date;
}
//# sourceMappingURL=openaiMessage.d.ts.map