/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface OpenaiConversation {
    id: number;
    title: string;
    createdAt: Date;
}
//# sourceMappingURL=openaiConversation.d.ts.map