/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { RecommendationPriority } from './recommendationPriority';
export interface Recommendation {
    id: number;
    /** @nullable */
    threatId?: number | null;
    title: string;
    description: string;
    priority: RecommendationPriority;
    actionType: string;
    isApplied: boolean;
    createdAt: Date;
}
//# sourceMappingURL=recommendation.d.ts.map