/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
export type RecommendationPriority = typeof RecommendationPriority[keyof typeof RecommendationPriority];
export declare const RecommendationPriority: {
    readonly immediate: "immediate";
    readonly high: "high";
    readonly medium: "medium";
    readonly low: "low";
};
//# sourceMappingURL=recommendationPriority.d.ts.map