/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface SecurityEvent {
    id: number;
    /** @nullable */
    threatId?: number | null;
    eventType: string;
    sourceIp: string;
    targetSystem: string;
    severity: string;
    details: string;
    timestamp: Date;
}
//# sourceMappingURL=securityEvent.d.ts.map