/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { ThreatInputSeverity } from './threatInputSeverity';

export interface ThreatInput {
  type: string;
  severity: ThreatInputSeverity;
  sourceIp: string;
  targetSystem: string;
  description: string;
  country?: string;
  attackVector?: string;
  affectedUsers?: number;
}
