/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */

export type ThreatStatus = typeof ThreatStatus[keyof typeof ThreatStatus];


export const ThreatStatus = {
  active: 'active',
  blocked: 'blocked',
  investigating: 'investigating',
  resolved: 'resolved',
} as const;
