/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */

export type ThreatInputSeverity = typeof ThreatInputSeverity[keyof typeof ThreatInputSeverity];


export const ThreatInputSeverity = {
  critical: 'critical',
  high: 'high',
  medium: 'medium',
  low: 'low',
} as const;
