/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * SENTINELX AI Cybersecurity Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { ThreatSeverity } from './threatSeverity';
import type { ThreatStatus } from './threatStatus';

export interface Threat {
  id: number;
  type: string;
  severity: ThreatSeverity;
  status: ThreatStatus;
  sourceIp: string;
  targetSystem: string;
  description: string;
  /** @nullable */
  aiExplanation?: string | null;
  /** @nullable */
  aiConfidence?: number | null;
  /** @nullable */
  mitigationSteps?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  attackVector?: string | null;
  /** @nullable */
  affectedUsers?: number | null;
  detectedAt: Date;
  updatedAt: Date;
}
